// <auto-generated />
using System;
using BibleStudyTool.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace BibleStudyTool.Infrastructure.Data.Migrations
{
    [DbContext(typeof(BibleReadingDbContext))]
    partial class BibleReadingDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.10")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("BibleStudyTool.Core.Entities.BibleBook", b =>
                {
                    b.Property<int>("BibleBookId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("DefaultName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("BibleBookDefaultName");

                    b.HasKey("BibleBookId");

                    b.ToTable("BibleBooks");
                });

            modelBuilder.Entity("BibleStudyTool.Core.Entities.BibleVerse", b =>
                {
                    b.Property<int>("BibleVerseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("BibleBookId")
                        .HasColumnType("integer");

                    b.Property<int>("ChapterNumber")
                        .HasColumnType("integer");

                    b.Property<bool>("IsNewTestament")
                        .HasColumnType("boolean");

                    b.Property<int>("VerseNumber")
                        .HasColumnType("integer");

                    b.HasKey("BibleVerseId");

                    b.HasIndex("BibleBookId");

                    b.ToTable("BibleVerses");
                });

            modelBuilder.Entity("BibleStudyTool.Core.Entities.BibleVersion", b =>
                {
                    b.Property<int>("BibleVersionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("DefaultAbbreviation")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("BibleVersionDefaultAbbreviation");

                    b.Property<string>("DefaultName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("BibleVersionDefaultName");

                    b.HasKey("BibleVersionId");

                    b.ToTable("BibleVersions");
                });

            modelBuilder.Entity("BibleStudyTool.Core.Entities.JoinEntities.BibleBookAbbreviationLanguage", b =>
                {
                    b.Property<int>("BibleBookId")
                        .HasColumnType("integer");

                    b.Property<string>("LanguageCode")
                        .HasColumnType("text");

                    b.Property<string>("Abbreviation")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("BibleBookAbbreviation");

                    b.Property<string>("Style")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("BibleBookAbbreviationStyle");

                    b.HasKey("BibleBookId", "LanguageCode");

                    b.HasIndex("LanguageCode");

                    b.ToTable("BibleBookAbbreviationLanguage");
                });

            modelBuilder.Entity("BibleStudyTool.Core.Entities.JoinEntities.BibleBookLanguage", b =>
                {
                    b.Property<int>("BibleBookId")
                        .HasColumnType("integer");

                    b.Property<string>("LanguageCode")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("BibleBookName");

                    b.Property<string>("Style")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("BibleBookNameStyle");

                    b.HasKey("BibleBookId", "LanguageCode");

                    b.HasIndex("LanguageCode");

                    b.ToTable("BibleBookLanguage");
                });

            modelBuilder.Entity("BibleStudyTool.Core.Entities.JoinEntities.BibleVerseBibleVersionLanguage", b =>
                {
                    b.Property<int>("BibleVerseId")
                        .HasColumnType("integer");

                    b.Property<int>("BibleVersionId")
                        .HasColumnType("integer");

                    b.Property<string>("LanguageCode")
                        .HasColumnType("text");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("BibleVerseBibleVersionLanguageText");

                    b.HasKey("BibleVerseId", "BibleVersionId", "LanguageCode");

                    b.HasIndex("BibleVersionId");

                    b.HasIndex("LanguageCode");

                    b.ToTable("BibleVerseBibleVersionLanguage");
                });

            modelBuilder.Entity("BibleStudyTool.Core.Entities.JoinEntities.BibleVersionLanguage", b =>
                {
                    b.Property<int>("BibleVersionId")
                        .HasColumnType("integer");

                    b.Property<string>("LanguageCode")
                        .HasColumnType("text");

                    b.Property<string>("Abbreviation")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("BibleVersionAbbreviation");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("BibleVersionName");

                    b.HasKey("BibleVersionId", "LanguageCode");

                    b.HasIndex("LanguageCode");

                    b.ToTable("BibleVersionLanguage");
                });

            modelBuilder.Entity("BibleStudyTool.Core.Entities.JoinEntities.NoteReference", b =>
                {
                    b.Property<int>("NoteReferenceSurrogateKey")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("NoteId")
                        .HasColumnType("integer");

                    b.Property<int?>("ReferencedBibleVerseId")
                        .HasColumnType("integer");

                    b.Property<int?>("ReferencedNoteId")
                        .HasColumnType("integer");

                    b.HasKey("NoteReferenceSurrogateKey");

                    b.HasIndex("NoteId");

                    b.HasIndex("ReferencedNoteId");

                    b.ToTable("NoteReferences");
                });

            modelBuilder.Entity("BibleStudyTool.Core.Entities.JoinEntities.TagGroupTag", b =>
                {
                    b.Property<int>("TagGroupId")
                        .HasColumnType("integer");

                    b.Property<int>("TagId")
                        .HasColumnType("integer");

                    b.HasKey("TagGroupId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("TagGroupTags");
                });

            modelBuilder.Entity("BibleStudyTool.Core.Entities.JoinEntities.TagNote", b =>
                {
                    b.Property<int>("TagId")
                        .HasColumnType("integer");

                    b.Property<int>("NoteId")
                        .HasColumnType("integer");

                    b.HasKey("TagId", "NoteId");

                    b.HasIndex("NoteId");

                    b.ToTable("TagNotes");
                });

            modelBuilder.Entity("BibleStudyTool.Core.Entities.Language", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("text");

                    b.Property<string>("Endonym")
                        .HasMaxLength(70)
                        .HasColumnType("character varying(70)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("character varying(70)")
                        .HasColumnName("LanguageName");

                    b.HasKey("Code");

                    b.ToTable("Languages");
                });

            modelBuilder.Entity("BibleStudyTool.Core.Entities.Note", b =>
                {
                    b.Property<int>("NoteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(240)
                        .HasColumnType("character varying(240)")
                        .HasColumnName("NoteSummary");

                    b.Property<string>("Text")
                        .HasColumnType("text")
                        .HasColumnName("NoteText");

                    b.Property<string>("Uid")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("NoteUid");

                    b.HasKey("NoteId");

                    b.ToTable("Notes");
                });

            modelBuilder.Entity("BibleStudyTool.Core.Entities.Tag", b =>
                {
                    b.Property<int>("TagId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Color")
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)")
                        .HasColumnName("TagColor");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("TagLabel");

                    b.Property<string>("Uid")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("TagUid");

                    b.HasKey("TagId");

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("BibleStudyTool.Core.Entities.TagGroup", b =>
                {
                    b.Property<int>("TagGroupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Uid")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("TagGroupUid");

                    b.HasKey("TagGroupId");

                    b.ToTable("TagGroups");
                });

            modelBuilder.Entity("BibleStudyTool.Infrastructure.Data.Identity.BibleReader", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("BibleReaders");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("BibleStudyTool.Core.Entities.BibleVerse", b =>
                {
                    b.HasOne("BibleStudyTool.Core.Entities.BibleBook", "BibleBook")
                        .WithMany("BibleVerses")
                        .HasForeignKey("BibleBookId")
                        .IsRequired();

                    b.Navigation("BibleBook");
                });

            modelBuilder.Entity("BibleStudyTool.Core.Entities.JoinEntities.BibleBookAbbreviationLanguage", b =>
                {
                    b.HasOne("BibleStudyTool.Core.Entities.BibleBook", "BibleBook")
                        .WithMany("BibleBookAbbreviationLanguages")
                        .HasForeignKey("BibleBookId")
                        .IsRequired();

                    b.HasOne("BibleStudyTool.Core.Entities.Language", "Language")
                        .WithMany("BibleBookAbbreviationLanguages")
                        .HasForeignKey("LanguageCode")
                        .IsRequired();

                    b.Navigation("BibleBook");

                    b.Navigation("Language");
                });

            modelBuilder.Entity("BibleStudyTool.Core.Entities.JoinEntities.BibleBookLanguage", b =>
                {
                    b.HasOne("BibleStudyTool.Core.Entities.BibleBook", "BibleBook")
                        .WithMany("BibleBookLanguages")
                        .HasForeignKey("BibleBookId")
                        .IsRequired();

                    b.HasOne("BibleStudyTool.Core.Entities.Language", "Language")
                        .WithMany("BibleBookLanguages")
                        .HasForeignKey("LanguageCode")
                        .IsRequired();

                    b.Navigation("BibleBook");

                    b.Navigation("Language");
                });

            modelBuilder.Entity("BibleStudyTool.Core.Entities.JoinEntities.BibleVerseBibleVersionLanguage", b =>
                {
                    b.HasOne("BibleStudyTool.Core.Entities.BibleVerse", "BibleVerse")
                        .WithMany("BibleVerseBibleVersionLanguages")
                        .HasForeignKey("BibleVerseId")
                        .IsRequired();

                    b.HasOne("BibleStudyTool.Core.Entities.BibleVersion", "BibleVersion")
                        .WithMany("BibleVerseBibleVersionLanguages")
                        .HasForeignKey("BibleVersionId")
                        .IsRequired();

                    b.HasOne("BibleStudyTool.Core.Entities.Language", "Language")
                        .WithMany("BibleVerseBibleVersionLanguages")
                        .HasForeignKey("LanguageCode")
                        .IsRequired();

                    b.Navigation("BibleVerse");

                    b.Navigation("BibleVersion");

                    b.Navigation("Language");
                });

            modelBuilder.Entity("BibleStudyTool.Core.Entities.JoinEntities.BibleVersionLanguage", b =>
                {
                    b.HasOne("BibleStudyTool.Core.Entities.BibleVersion", "BibleVersion")
                        .WithMany("BibleVersionLanguages")
                        .HasForeignKey("BibleVersionId")
                        .IsRequired();

                    b.HasOne("BibleStudyTool.Core.Entities.Language", "Language")
                        .WithMany("BibleVersionLanguages")
                        .HasForeignKey("LanguageCode")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.Navigation("BibleVersion");

                    b.Navigation("Language");
                });

            modelBuilder.Entity("BibleStudyTool.Core.Entities.JoinEntities.NoteReference", b =>
                {
                    b.HasOne("BibleStudyTool.Core.Entities.Note", "Note")
                        .WithMany("ReferencedIn")
                        .HasForeignKey("NoteId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.HasOne("BibleStudyTool.Core.Entities.BibleVerse", "ReferencedBibleVerse")
                        .WithMany("ReferencedNotes")
                        .HasForeignKey("ReferencedNoteId")
                        .OnDelete(DeleteBehavior.ClientCascade);

                    b.HasOne("BibleStudyTool.Core.Entities.Note", "ReferencedNote")
                        .WithMany("ReferencedNotes")
                        .HasForeignKey("ReferencedNoteId")
                        .OnDelete(DeleteBehavior.ClientCascade);

                    b.Navigation("Note");

                    b.Navigation("ReferencedBibleVerse");

                    b.Navigation("ReferencedNote");
                });

            modelBuilder.Entity("BibleStudyTool.Core.Entities.JoinEntities.TagGroupTag", b =>
                {
                    b.HasOne("BibleStudyTool.Core.Entities.TagGroup", "TagGroup")
                        .WithMany("TagGroupTags")
                        .HasForeignKey("TagGroupId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.HasOne("BibleStudyTool.Core.Entities.Tag", "Tag")
                        .WithMany("TagGroupTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.Navigation("Tag");

                    b.Navigation("TagGroup");
                });

            modelBuilder.Entity("BibleStudyTool.Core.Entities.JoinEntities.TagNote", b =>
                {
                    b.HasOne("BibleStudyTool.Core.Entities.Note", "Note")
                        .WithMany("TagNotes")
                        .HasForeignKey("NoteId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.HasOne("BibleStudyTool.Core.Entities.Tag", "Tag")
                        .WithMany("TagNotes")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.Navigation("Note");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("BibleStudyTool.Infrastructure.Data.Identity.BibleReader", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("BibleStudyTool.Infrastructure.Data.Identity.BibleReader", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BibleStudyTool.Infrastructure.Data.Identity.BibleReader", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("BibleStudyTool.Infrastructure.Data.Identity.BibleReader", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BibleStudyTool.Core.Entities.BibleBook", b =>
                {
                    b.Navigation("BibleBookAbbreviationLanguages");

                    b.Navigation("BibleBookLanguages");

                    b.Navigation("BibleVerses");
                });

            modelBuilder.Entity("BibleStudyTool.Core.Entities.BibleVerse", b =>
                {
                    b.Navigation("BibleVerseBibleVersionLanguages");

                    b.Navigation("ReferencedNotes");
                });

            modelBuilder.Entity("BibleStudyTool.Core.Entities.BibleVersion", b =>
                {
                    b.Navigation("BibleVerseBibleVersionLanguages");

                    b.Navigation("BibleVersionLanguages");
                });

            modelBuilder.Entity("BibleStudyTool.Core.Entities.Language", b =>
                {
                    b.Navigation("BibleBookAbbreviationLanguages");

                    b.Navigation("BibleBookLanguages");

                    b.Navigation("BibleVerseBibleVersionLanguages");

                    b.Navigation("BibleVersionLanguages");
                });

            modelBuilder.Entity("BibleStudyTool.Core.Entities.Note", b =>
                {
                    b.Navigation("ReferencedIn");

                    b.Navigation("ReferencedNotes");

                    b.Navigation("TagNotes");
                });

            modelBuilder.Entity("BibleStudyTool.Core.Entities.Tag", b =>
                {
                    b.Navigation("TagGroupTags");

                    b.Navigation("TagNotes");
                });

            modelBuilder.Entity("BibleStudyTool.Core.Entities.TagGroup", b =>
                {
                    b.Navigation("TagGroupTags");
                });
#pragma warning restore 612, 618
        }
    }
}
